name: personaltaskmanager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  modal_progress_hud_nsn: ^0.5.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  calendar_date_picker2: ^1.0.2
  awesome_snackbar_content: ^0.1.3
  connectivity_plus: 5.0.0
  alarm: ^3.1.4
  flutter_holo_date_picker: ^1.1.3
  flutter_swipe_action_cell: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
  fonts:
     - family: sketch
       fonts:
         - asset: fonts/sketchgothic.ttf
     - family: germenia
       fonts:
         - asset: fonts/germenia.ttf
     - family: praetoria
       fonts:
         - asset: fonts/praetoria.otf
